### ISSUE TITLE
Formatting leads to additional columns after saving

### ISSUE THREAD

**Issue by ToGe88** [bogdancondorachi/kirby-table-field#11] opened 2024-05-30 18:43 UTC
So there is a very specific problem with the table formatting on save, i think. Here is what i found out so far:

When i type a quite long content inside a cell such as this (currently an exhibition title):
<img width="565" alt="Bildschirmfoto 2024-05-30 um 20 38 40" src="https://github.com/bogdancondorachi/kirby-table-field/assets/8841530/7b193c89-468f-456a-ab24-dc7ee1aa4495">

and click safe, the plugin formats it to this:
<img width="565" alt="Bildschirmfoto 2024-05-30 um 20 38 54" src="https://github.com/bogdancondorachi/kirby-table-field/assets/8841530/fa010d40-b734-4c28-b279-c3f2cf02d739">

and in the content file to this:
<img width="456" alt="Bildschirmfoto 2024-05-30 um 20 39 22" src="https://github.com/bogdancondorachi/kirby-table-field/assets/8841530/2883318b-c641-4478-90b4-6a4cad050620">

Unfortunately this happens whenever the page is safed. Currently i am on dev mode, but think it will be a problem when the page is live and the user wants to edit the table, which will happen some time since it is a client's CV Page.

Is there any possibility to prevent this behaviour?

**Comment by gbdesign2023** [comment] 2024-05-30 18:54
@ToGe88 I have been using the plugin successfully since the beginning, on almost all my installations. 
Unfortunately, I could not reproduce the problem you described. I have tried it with very long continuous text and also with manual line breaks. The text was saved and displayed correctly. 
Did you copy and paste the text or write it manually in the field? 
Can you post the code from the blueprint?

**Comment by ToGe88** [comment] 2024-05-30 19:16
<img width="587" alt="image" src="https://github.com/bogdancondorachi/kirby-table-field/assets/8841530/1d970771-2568-4bf7-b784-a39efee8e4a7">
It even happens when i type in long content like above. Blueprint is pretty straight-forward.
<img width="206" alt="image" src="https://github.com/bogdancondorachi/kirby-table-field/assets/8841530/7c8562e0-7b83-4f79-beb8-c90708460567">
Using Chrome on a Mac

**Comment by gbdesign2023** [comment] 2024-05-30 19:28
@ToGe88 I have tried to reproduce your procedure. The text is saved as expected and also looks good in the .txt. 
I assume you are using the latest version of the plug-in and Kirby 4.2? 
It's best to wait for a response from @bogdancondorachi Maybe he can help.

<img width="853" alt="table" src="https://github.com/bogdancondorachi/kirby-table-field/assets/140849227/e306dc27-7967-4048-9bed-257f2ef4dc0c">


```
"table": [
    [
        "",
        "",
        ""
    ],
    [
        "",
        "THE EYES THAT SAW <br>THE LIGHT MELTED<br>OUT OF SHEER <br>ECSTASY. BURN",
        "Brock Lesnar Proj"
    ]
]
```

**Comment by gbdesign2023** [comment] 2024-05-30 19:48
@ToGe88 I have now been able to reproduce the problem when I use a table as a field. The problem does not occur with a block/layout.  

<img width="870" alt="tabel-test" src="https://github.com/bogdancondorachi/kirby-table-field/assets/140849227/40858c04-4b07-4b1f-b10c-a374f796cf99">

**Comment by twiro** [comment] 2024-06-10 21:16
I can confirm the buggy behavior described in this thread and noticed that the problem always appears whenever I type **more than 40 characters** in one cell _(when the table is used as a field, not a block,as mentioned above)_

With _"Lorem Ipsum Lorem Ipsum Lorem Ipsum Lore"_ my table looks just fine and if I check the content in my .txt file it looks like this…

```
- 
  - ""
  - Lorem Ipsum Lorem Ipsum Lorem Ipsum Lore
  - ""
```

… but as soon as I add one more character and type _"Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem"_ the whole table layout gets blown up and when I check the content in my .txt it has turned into this:

```
- 
  - ""
  - >
    Lorem Ipsum Lorem Ipsum Lorem Ipsum
    Lorem
  - ""
```

This formatting in the txt-file always seems to result in two additional columns in that specific row of the table layout and a weird behaviour in cell height all over the table.

And it can't be fixed by simply deleting the content of the concerned cells, the whole row has to be deleted to return to a well formatted table.

Would be awesome if you could release a fix for this bug, as it is a real showstopper for using tables as fields at the moment.

**(My Setup is Kirby 4.2.0 and the latest release of this plugin)**

**Closed** 2024-11-27 19:31 UTC
Labels: type: regression 🚨, needs: testing 🧪
